version: "3.5"

services:
  server:
    build:
      context: './'
      dockerfile: Dockerfile
    tty: true
    env_file: 
      - .env
    volumes:
      - .:/opt/server
      - ./storage:/var/storage
    ports:
      - "8000:8000"
    command: make run

  quasselcore:
    build:
      context: './'
      dockerfile: Dockerfile-quasselcore
    volumes:
      - ./storage:/var/storage
    ports:
      - "4242:4242"
    command: quasselcore --configdir=/var/storage/quassel
