version: "3.5"

services:
  server:
    build:
      context: './'
      dockerfile: Dockerfile
    tty: true
    environment:
      PYTHONPATH: /opt/server/floodlair
      NUM_WORKERS: 2
    env_file: 
      - .env
    volumes:
      - .:/opt/server
      - ./storage:/var/storage
    ports:
      - "8000:8000"
    command: make run
