version: "3.5"

services:
  server:
    build:
      context: './'
      dockerfile: Dockerfile
    tty: true
    environment:
      PYTHONPATH: /opt/server/floodlair
      NUM_WORKERS: 2
    env_file: 
      - .env
    volumes:
      - .:/opt/server
      - ./storage:/var/storage
    ports:
      - "8000:8000"
    command: make rundebug

  nginx:
    image: nginx
    ports:
      - "5001:5001"
    volumes:
      - .:/opt/server
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf
    depends_on:
      - server
