version: "3.5"

services:
  server:
    build:
      context: './'
      dockerfile: Dockerfile
    tty: true
    environment: : 
      DB_FILE=/var/storage/quassel/quassel-storage.sqlite
      BUFFERID=7
    volumes:
      - .:/opt/server
      - /mnt/volume_ams3_01/:/var/storage
    ports:
      - "8000:8000"
    command: make run

  quasselcore:
    build:
      context: './'
      dockerfile: Dockerfile-quasselcore
    volumes:
      - /mnt/volume_ams3_01/:/var/storage
    ports:
      - "4242:4242"
    command: quasselcore --configdir=/var/storage/quassel
